namespace MonkeyCode
{
    public enum TokenType
    {
        BooleanTypeKeyword,
        IntegerTypeKeyword,
        StringTypeKeyword,
        FloatTypeKeyword,
        BooleanTrueLiteral,
        BooleanFalseLiteral,
        String,
        Integer,
        Identifier,
        OperatorLeftParen,
        OperatorRightParen,
        OperatorSemicolon,
        OperatorEquals,
        OperatorNotEquals,
        OperatorGreaterThan,
        OperatorLessThan,
        OperatorGreaterThanEqualTo,
        OperatorLessThanEqualTo,
        OperatorNot,
        Plus,
        Minus,
        Multiply,
        Divide,
        InfiniteKeyword,
        BreakKeyword,
        IfKeyword,
        ForeverKeyword,
        OperatorLeftBracket,
        OperatorRightBracket,
        PrintKeyword
    }
}